# Generated by Django 4.2.4 on 2023-08-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_borrowing_expected_return_date_borrow_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                check=models.Q(("actual_return_date__gte", models.F("borrow_date"))),
                name="actual_return_date >= borrow_date",
            ),
        ),
    ]
