# Generated by Django 4.2.4 on 2023-08-12 06:45

import borrowings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_author_remove_book_author_book_authors"),
        ("borrowings", "0005_alter_borrowing_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowing",
                to="books.book",
                validators=[borrowings.models.validate_book_inventory],
            ),
        ),
    ]
