# Generated by Django 4.2.4 on 2023-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0006_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
